<?php

$fields = [

'strProductSKU',
'strBrandName',
'strDepartment',
'strSubCategory',
'dblProductSalePrice',
'txtLongDescription',
'strThumbnailImage',
'strLargeImage',
'txtProductReviews',
'strBrandLogoImage',
'strProductName',
'strManufacturerPartNumber',
'strCategory',
'dblProductPrice',
'txtShortDescription',
'txtProductKeywords',
'strMediumImage',
'strBuyURL',
'strBrandURL',
'dblItemCommission',
'strCategorization',
'strAttribute1',
'strAttribute2',
'strAttribute3',
'strAttribute4',
'strAttribute5',
'strAttribute6',
'strAttribute7',
'strAttribute8',
'strAttribute9',
'strAttribute10',
'intAttribute1',
'intAttribute2',
'intAttribute3',
'intAttribute4',
'txtAttribute1',
'txtAttribute2',
'txtAttribute3',
'txtAttribute4',
'txtAttribute5',
'txtAttribute6',
'txtAttribute7',
'txtAttribute8',
'txtAttribute9',
'txtAttribute10'

];

?>
